from __future__ import annotations

APP_NAME = "trading-bot"

LOG_DIR_DEFAULT = "./logs"
DATA_DIR_DEFAULT = "./data"

DECISION_STATUS_SKIPPED = "SKIPPED"
DECISION_STATUS_OPENED = "OPENED"
DECISION_STATUS_CLOSED = "CLOSED"
DECISION_STATUS_NO_SIGNAL = "NO_SIGNAL"
DECISION_STATUS_RISK_BLOCKED = "RISK_BLOCKED"
DECISION_STATUS_ERROR = "ERROR"

